# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: nagarajeshreddythallapureddy@gmail.com
author_name: thallapureddynagarajesh
contract_name: land_contract
deployment_language: python
preset_name: production
project_name: land_chain-contracts

